export CONFIG_TARGET = aarch64-linux-gnu
export CONFIG_LINUX_ARCH = arm64
export CONFIG_LINUX_KERNEL_DEFCONFIG = bcm2711_defconfig
export CONFIG_STRIP_AND_DELETE_DOCS = 1
export CONFIG_HOSTNAME = qnas
export CONFIG_ROOT_PASSWD = qnas
export CONFIG_IMAGE_FILENAME = QNAS-1.0.0-Absinthe-RPi4.img
export CONFIG_ROOTFS_IMAGE_SIZE = 130M
