#!/bin/sh
DESC="MinIO object storage server"
NAME=minio
DAEMON=/bin/minio
PIDFILE=/var/run/$NAME.pid
DAEMONOPTS="server /srv/minio --config-dir /srv/minio-config --console-address :9000 --address :9001"

test -x $DAEMON || exit 0

# Set the ulimits
ulimit -n 8192

start() {
    export MINIO_ROOT_USER=qnas
    export MINIO_ROOT_PASSWORD=qnas_minio_server
    start-stop-daemon -S -q -b -p $PIDFILE -m -x $DAEMON -- $DAEMONOPTS
    if [ "$?" -eq 0 ]; then
        echo "OK"
    else
        echo "FAIL"
    fi
    unset MINIO_ROOT_USER MINIO_ROOT_PASSWORD
}

stop() {
    start-stop-daemon -K -q -p $PIDFILE
    if [ "$?" -eq 0 ]; then
        echo "OK"
    else
        echo "FAIL"
    fi
    rm -f $PIDFILE
}

status() {
    if [ -f $PIDFILE ]; then
        if kill -0 $(cat "$PIDFILE"); then
            echo "$NAME is running"
        else
            echo "$NAME process is dead, but pidfile exists"
        fi
    else
        echo "$NAME is not running"
    fi
}

case "$1" in
start)
    printf "Starting $NAME... "
    start
    ;;
stop)
    printf "Stopping $NAME... "
    stop
    ;;
restart)
    printf "Restarting $NAME"
    stop
    start
    ;;
status)
    status
    ;;
*)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 2
    ;;
esac

exit 0
